// Drivers for the tenant we WRITE to. Currently UAT (DAVISV5) — the enabled
// accounts that carry the NuVizz DI_Driver role (every user assignable as a load's
// driver). UAT is a shared NuVizz test sandbox, so this includes NuVizz internal
// test accounts; that's intentional. `userName` is the display key; `driverId`
// (= the roster userId) is what NuVizz's assignanddispatch needs.
//
// HOW THIS WAS BUILT (repeat for the DAVIS production switch):
//   POST {BASE}/user/list/{COMPANY}  (Basic auth = NUVIZZ_DAVIS_USER:PASS), body:
//   {"pageInfo":{"pageSize":0,"page":1,"maxResult":500},"searchCriteria":{...,"userRoles":["-1"],"status":"-1"}}
//   keep accountStatus==ENABLED with the DI_Driver role; driverId = each user's userId.
export const KNOWN_DRIVERS = [
  { userName: 'ABI', driverId: 25941, name: 'abi user', mobile: '' },
  { userName: 'ABI1', driverId: 33158, name: 'abi user', mobile: '' },
  { userName: 'AKASHD12', driverId: 33522, name: 'Akash D', mobile: '' },
  { userName: 'ARVDRIVER', driverId: 38806, name: 'arv driver', mobile: '9900990099' },
  { userName: 'ARVIND', driverId: 38803, name: 'arv ind', mobile: '9900990099' },
  { userName: 'GSHAFIULLA', driverId: 22269, name: 'Attar Shafi', mobile: '' },
  { userName: 'BHARGAV', driverId: 54607, name: 'Bhargav Nuvizz', mobile: '' },
  { userName: 'BILL', driverId: 44239, name: 'Bill Bill', mobile: '' },
  { userName: 'CHAD', driverId: 20367, name: 'Chad Davis', mobile: '' },
  { userName: 'DPATIL', driverId: 40411, name: 'D Patil', mobile: '' },
  { userName: 'DADMIN', driverId: 18281, name: 'Davis admin', mobile: '' },
  { userName: 'DIBYASINGH', driverId: 49872, name: 'Dibyasingh Pallai', mobile: '' },
  { userName: 'DILIP', driverId: 35476, name: 'dilip s', mobile: '' },
  { userName: 'GREG', driverId: 19845, name: 'Greg P', mobile: '' },
  { userName: 'HBATTULURI', driverId: 25709, name: 'hareesh battuluri', mobile: '8977819802' },
  { userName: 'HARISHKC', driverId: 31115, name: 'Harish K C', mobile: '9108838757' },
  { userName: 'HARSHA', driverId: 56184, name: 'Harsha S', mobile: '' },
  { userName: 'HARSHAV5', driverId: 54234, name: 'Harsha SV5', mobile: '' },
  { userName: 'HIDAYATH', driverId: 34602, name: 'Hidayath N', mobile: '' },
  { userName: 'HBASHA1', driverId: 35142, name: 'hussain basha', mobile: '' },
  { userName: 'HBASHA', driverId: 31863, name: 'hussain basha', mobile: '7019284811' },
  { userName: 'IMRAN', driverId: 25427, name: 'Imran V5', mobile: '' },
  { userName: 'JAMES12', driverId: 35484, name: 'James P', mobile: '' },
  { userName: 'JAVEED', driverId: 53037, name: 'Javeed S', mobile: '' },
  { userName: 'JEET', driverId: 25693, name: 'jeet singh Poonia', mobile: '' },
  { userName: 'JIYO', driverId: 32416, name: 'Jiyo G', mobile: '' },
  { userName: 'JOHN12', driverId: 23361, name: 'John Mike', mobile: '' },
  { userName: 'JOHN', driverId: 19827, name: 'John Shelby', mobile: '' },
  { userName: 'SHERRY', driverId: 23363, name: 'john sherry', mobile: '' },
  { userName: 'KRISH2233', driverId: 28867, name: 'krishna dodamani', mobile: '' },
  { userName: 'LDR1', driverId: 25437, name: 'Libin Driver', mobile: '' },
  { userName: 'MKUMAR', driverId: 20253, name: 'Mala Madhukumar', mobile: '' },
  { userName: 'MANOJ12', driverId: 34716, name: 'Manoj Kumar', mobile: '' },
  { userName: 'NINJA', driverId: 49155, name: 'Ninja Hatoori', mobile: '' },
  { userName: 'PILOTDEV1', driverId: 43516, name: 'Pilot Dev1', mobile: '' },
  { userName: 'PIYUSH', driverId: 52529, name: 'piyush nuvizz', mobile: '' },
  { userName: 'PRAGATHI', driverId: 37303, name: 'Pragathi B', mobile: '' },
  { userName: 'RAKESH', driverId: 49900, name: 'Rakesh B', mobile: '' },
  { userName: 'ROHITH', driverId: 49530, name: 'Rohith B', mobile: '' },
  { userName: 'SROOPA', driverId: 29357, name: 'Roopa S', mobile: '' },
  { userName: 'SNEW', driverId: 48025, name: 'SNEW TEST', mobile: '' },
  { userName: 'SREENATH', driverId: 25893, name: 'Sreenath Unni', mobile: '' },
  { userName: 'STEVE', driverId: 19843, name: 'steve M', mobile: '' },
  { userName: 'SUBIN', driverId: 35606, name: 'Subin P B', mobile: '' },
  { userName: '#SUMAN', driverId: 27341, name: 'Suman Rao', mobile: '' },
  { userName: 'SURYAD', driverId: 34068, name: 'surya davis', mobile: '8247438602' },
  { userName: 'SUSHANTHS', driverId: 22277, name: 'Sushanth S', mobile: '' },
  { userName: 'TESTMEMBER', driverId: 39730, name: 'Test member', mobile: '9988776655' },
  { userName: 'SHELBY', driverId: 39427, name: 'Thomas Shelby', mobile: '' },
  { userName: 'VENU', driverId: 52488, name: 'Venu C', mobile: '' },
  { userName: 'VICKY', driverId: 27339, name: 'Vicky D', mobile: '' },
  { userName: 'VIZZRAO', driverId: 22343, name: 'Vizz Rao', mobile: '4046633294' },
  { userName: 'ZACH', driverId: 53709, name: 'Zach Johnston', mobile: '' },
]
